[workspace]
resolver = "2"
members = ["test-vectors"]

[workspace.dependencies]
# Third party dependencies
anyhow = "1.0.100"
hex = { version = "0.4.3", features = ["serde"] }
ron = "0.12.0"
rstest = "0.26.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.16.1", features = ["hex"] }
tpm2-rs-client = { git = "https://github.com/tpm-rs/tpm-rs.git" }

# Common workspace crates
tpm2-test-vectors = { path = "test-vectors" }

[profile.release]
lto = true        # default is lto = false
codegen-units = 1 # default is codegen-units = 16
strip = true      # default is strip = "none"
