[workspace]
resolver = "2"
members = ["test-vectors"]

[workspace.dependencies]
# Third party dependencies
hex = { version = "0.4.3", features = ["serde"] }
ron = "0.12.0"

# Common workspace crates
tpm2-test-vectors = { path = "test-vectors" }

[profile.release]
lto = true        # default is lto = false
codegen-units = 1 # default is codegen-units = 16
strip = true      # default is strip = "none"
