[package]
name = "tpm2-test-vectors"
version = "0.1.0"
edition = "2024"

[dependencies]
const_format = { workspace = true }
hex = { workspace = true }
nom = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
tpm2-client = { workspace = true }
