[package]
name = "tpm2-test-vectors"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rstest = { workspace = true }
tpm2-rs-client = { workspace = true }
